### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by KoalaGeo** [AuScope/geomodelportal#4]
Hi, 

Trying to install on a new machine and npm install seems to go ok, but npm start I'm getting the error below

Any ideas? 

edd@edd-VirtualBox:~/Documents/gitkraken/geomodelportal/ui$ npm start

> geomodelportal@1.0.0 start /home/edd/Documents/gitkraken/geomodelportal/ui
> ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --disableHostCheck

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geomodelportal@1.0.0 start: `ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --disableHostCheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geomodelportal@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edd/.npm/_logs/2020-04-02T09_07_39_143Z-debug.log

Log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle geomodelportal@1.0.0~prestart: geomodelportal@1.0.0
6 info lifecycle geomodelportal@1.0.0~start: geomodelportal@1.0.0
7 verbose lifecycle geomodelportal@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle geomodelportal@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/edd/Documents/gitkraken/geomodelportal/ui/node_modules/.bin:/home/edd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle geomodelportal@1.0.0~start: CWD: /home/edd/Documents/gitkraken/geomodelportal/ui
10 silly lifecycle geomodelportal@1.0.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --disableHostCheck'
10 silly lifecycle ]
11 silly lifecycle geomodelportal@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle geomodelportal@1.0.0~start: Failed to exec start script
13 verbose stack Error: geomodelportal@1.0.0 start: `ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --disableHostCheck`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid geomodelportal@1.0.0
15 verbose cwd /home/edd/Documents/gitkraken/geomodelportal/ui
16 verbose Linux 5.3.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error geomodelportal@1.0.0 start: `ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --disableHostCheck`
22 error Exit status 1
23 error Failed at the geomodelportal@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by stuartwoodman** [comment]
Have you tried cleaning the npm cache? I found these steps recommended for a similar problem:

-  'npm cache clean --force'
-  delete node_modules folder
-  delete package-lock.json file
-  npm install

**Comment by KoalaGeo** [comment]
@stuartwoodman that did it, thank you!
